// Code generated by tygo. DO NOT EDIT.
// Generated from the Go structs in backend/internal/apitypes.
// Do not edit this file by hand -- run `make gen-types` instead.

//////////
// source: apitypes.go


/**
 * A single point on a metric chart, as [x, y].
 */
export type MetricPoint = [number, number];

/**
 * RepoKind is the kind of artifact a repository holds.
 */
export const RepoKindDataset = "dataset";
export const RepoKindModel = "model";
export type RepoKind = typeof RepoKindDataset | typeof RepoKindModel;
/**
 * NamespaceKind distinguishes a personal namespace from an organisation.
 */
export const NamespaceKindUser = "user";
export const NamespaceKindOrg = "org";
export type NamespaceKind = typeof NamespaceKindUser | typeof NamespaceKindOrg;
/**
 * TokenScope is the access level granted to an API token.
 */
export const TokenScopeRead = "read";
export const TokenScopeWrite = "write";
export type TokenScope = typeof TokenScopeRead | typeof TokenScopeWrite;
/**
 * EntryType tells a directory listing entry apart from a file.
 */
export const EntryTypeFile = "file";
export const EntryTypeDirectory = "directory";
export type EntryType = typeof EntryTypeFile | typeof EntryTypeDirectory;
/**
 * PreviewKind names the viewer the web UI should open a file with. It is the
 * empty string for directories, which have no preview.
 */
export const PreviewKindNone = "";
export const PreviewKindParquet = "parquet";
export const PreviewKindModel = "model";
export const PreviewKindText = "text";
export const PreviewKindImage = "image";
export const PreviewKindMarkdown = "markdown";
export const PreviewKindBinary = "binary";
export type PreviewKind = typeof PreviewKindNone | typeof PreviewKindParquet | typeof PreviewKindModel | typeof PreviewKindText | typeof PreviewKindImage | typeof PreviewKindMarkdown | typeof PreviewKindBinary;
/**
 * FileEncoding says how the bytes in a raw file response were encoded: valid
 * UTF-8 is passed through, anything else is base64.
 */
export const FileEncodingUTF8 = "utf-8";
export const FileEncodingBase64 = "base64";
export type FileEncoding = typeof FileEncodingUTF8 | typeof FileEncodingBase64;
/**
 * ModelFormat names a supported checkpoint container.
 */
export const ModelFormatSafetensors = "safetensors";
export const ModelFormatPyTorch = "pytorch";
export type ModelFormat = typeof ModelFormatSafetensors | typeof ModelFormatPyTorch;
/**
 * RunStatus is the lifecycle state of an experiment run.
 */
export const RunStatusRunning = "running";
export const RunStatusFinished = "finished";
export const RunStatusFailed = "failed";
export type RunStatus = typeof RunStatusRunning | typeof RunStatusFinished | typeof RunStatusFailed;
/**
 * Namespace is somewhere the user may create repositories.
 */
export interface Namespace {
  name: string;
  kind: NamespaceKind;
  /**
   * Role is the user's role in this namespace ("admin", "write", ...), or
   * "" when membership carries no explicit role.
   */
  role: string;
}
/**
 * User is the signed-in account as the web UI sees it.
 */
export interface User {
  id: number /* int64 */;
  username: string;
  email: string;
  is_admin: boolean;
  /**
   * DisplayName and AvatarURL come from the user's own namespace row
   * (docs/dev/namespace-design.md §5.3); both may be "".
   */
  display_name: string;
  avatar_url: string;
  namespaces: Namespace[];
}
/**
 * UserResponse wraps the account in the envelope /me, /login and /signup use.
 */
export interface UserResponse {
  user: User;
}
/**
 * NamespaceProfile is the public face of a namespace -- a user or an
 * organisation -- as GET /api/v1/namespaces/{ns} returns it
 * (docs/dev/namespace-design.md §7.1). Both kinds share the same profile
 * columns on the namespaces row; the organisation-only fields are zero for
 * a user namespace.
 */
export interface NamespaceProfile {
  /**
   * Name is the canonical spelling. Namespace names are case-insensitive,
   * so a lookup for "Alice" answers with Name "alice" when that is how the
   * account was registered; the UI redirects to the canonical URL.
   */
  name: string;
  kind: NamespaceKind;
  display_name: string;
  description: string;
  website: string;
  avatar_url: string;
  created_at: string;
  num_models: number /* int64 */;
  num_datasets: number /* int64 */;
  num_experiments: number /* int64 */;
  /**
   * NumMembers and MembersVisibility only mean something for an
   * organisation; a user namespace reports 0 and "".
   */
  num_members: number /* int64 */;
  members_visibility: MembersVisibility;
  /**
   * ViewerRole is the caller's effective role (docs/dev/organization-design.md
   * §3.1): "admin" for the owner of a user namespace and for a site admin,
   * the org_members role for an organisation, "" otherwise.
   */
  viewer_role: OrgRole;
  /**
   * CanEdit is ViewerRole == "admin", spelled out so the UI can show the
   * "Edit profile" / "Settings" button without re-deriving it.
   */
  can_edit: boolean;
}
/**
 * NamespaceResponse wraps one profile.
 */
export interface NamespaceResponse {
  namespace: NamespaceProfile;
}
/**
 * NamespaceProfileUpdate is the body of PATCH /api/v1/me/profile. Every
 * field is optional; a present field replaces the stored value (an empty
 * string clears it). The namespace name itself is not editable
 * (docs/dev/namespace-design.md §5.4).
 */
export interface NamespaceProfileUpdate {
  display_name?: string;
  description?: string;
  website?: string;
  avatar_url?: string;
}
/**
 * TokenItem is one API token, without its secret value.
 */
export interface TokenItem {
  id: number /* int64 */;
  name: string;
  scope: TokenScope;
  /**
   * CreatedAt is an RFC 3339 timestamp.
   */
  created_at: string;
  /**
   * LastUsedAt is null until the token authenticates a request.
   */
  last_used_at: string | null;
  /**
   * ExpiresAt is null for a token that never expires.
   */
  expires_at: string | null;
}
/**
 * TokenListResponse is the body of GET /api/v1/tokens.
 */
export interface TokenListResponse {
  items: TokenItem[];
}
/**
 * CreateTokenResponse returns the freshly minted token. The plaintext value
 * appears here and nowhere else, so a client that loses it must issue another.
 */
export interface CreateTokenResponse extends TokenItem {
  token: string;
}
/**
 * SSHKeyItem is one registered SSH public key. Unlike a token there is no
 * secret to withhold: the key material is public by construction, so it is
 * returned in full and the UI can show it.
 */
export interface SSHKeyItem {
  id: number /* int64 */;
  title: string;
  /**
   * KeyType is the algorithm name, e.g. "ssh-ed25519".
   */
  key_type: string;
  /**
   * PublicKey is the canonical "<type> <base64>" authorized_keys line,
   * with the comment stripped.
   */
  public_key: string;
  /**
   * Fingerprint is the OpenSSH "SHA256:<base64>" form, which is what
   * `ssh-keygen -lf` prints.
   */
  fingerprint: string;
  /**
   * CreatedAt is an RFC 3339 timestamp.
   */
  created_at: string;
  /**
   * LastUsedAt is null until the key authenticates an SSH session.
   */
  last_used_at: string | null;
}
/**
 * SSHKeyListResponse is the body of GET /api/v1/me/ssh-keys.
 */
export interface SSHKeyListResponse {
  items: SSHKeyItem[];
}
/**
 * RepoSummary is the repository shape used in listings and search results.
 */
export interface RepoSummary {
  id: number /* int64 */;
  kind: RepoKind;
  namespace: string;
  /**
   * NamespaceKind says whether Namespace is a user or an organisation, so
   * the UI can link to the right profile page.
   */
  namespace_kind: NamespaceKind;
  name: string;
  /**
   * FullName is "namespace/name".
   */
  full_name: string;
  description: string;
  tags: string[];
  /**
   * License is "" when the repository card does not name one.
   */
  license: string;
  downloads: number /* int64 */;
  /**
   * TotalSize is the sum of all file sizes, in bytes.
   */
  total_size: number /* int64 */;
  num_files: number /* int */;
  /**
   * IsExperiment marks a dataset repository holding tracked training runs.
   */
  is_experiment: boolean;
  default_branch: string;
  head_sha: string;
  created_at: string;
  updated_at: string;
  /**
   * Archived marks a read-only repository: it still resolves, clones and
   * downloads, but every write is refused with 403 until it is unarchived.
   */
  archived: boolean;
  /**
   * ArchivedAt is when it was archived, or null while it is active.
   */
  archived_at: string | null;
}
/**
 * ParquetSummary describes an indexed parquet file inside a repository.
 */
export interface ParquetSummary {
  path: string;
  num_rows: number /* int64 */;
  num_row_groups: number /* int */;
  num_columns: number /* int */;
  size: number /* int64 */;
}
/**
 * RepoDetail is the summary plus everything a repository page needs.
 */
export interface RepoDetail extends RepoSummary {
  /**
   * Card is the parsed YAML front matter of README.md.
   */
  card: { [key: string]: unknown};
  readme: string;
  /**
   * ReadmeTooLarge is true when README.md exists but exceeds the server's
   * size limit for rendering, in which case Readme is left empty instead of
   * silently looking like "no README". Card is unaffected: it comes from the
   * index built at push time, not from this read.
   */
  readme_too_large: boolean;
  clone_url: string;
  branches: string[];
  tags_refs: string[];
  /**
   * ParquetFiles lists the indexed parquet files on the default branch.
   */
  parquet_files: ParquetSummary[];
  /**
   * Indexing reports that a background index of this repository is running,
   * so ParquetFiles may still be incomplete.
   */
  indexing: boolean;
  /**
   * CanWrite tells the web UI whether to offer in-browser editing. It is
   * false for an archived repository even when the viewer would otherwise
   * have write access, so every editing affordance disappears at once.
   */
  can_write: boolean;
  /**
   * CanAdmin tells the web UI whether to offer the owner-only operations:
   * transfer, archive/unarchive and delete. Unlike CanWrite it stays true
   * while the repository is archived -- unarchiving it is exactly what an
   * owner needs to be able to do.
   */
  can_admin: boolean;
  /**
   * DownloadsLast30Days is the resolve-endpoint hit count for the trailing
   * 30 days. RepoSummary.Downloads (embedded above) stays the all-time
   * cumulative counter.
   */
  downloads_last_30_days: number /* int64 */;
}
/**
 * RepoDetailResponse wraps the repository page's data in its envelope.
 */
export interface RepoDetailResponse {
  repo: RepoDetail;
}
/**
 * RepoFacetItem is one value of a listing facet (a tag, a license, a task)
 * together with how many repositories in the current result set carry it.
 */
export interface RepoFacetItem {
  value: string;
  count: number /* int64 */;
}
/**
 * RepoFacets aggregates the filterable repository-card dimensions the
 * listing sidebar offers. Each facet is computed under every filter
 * currently applied except its own dimension, so picking a value shows how
 * many *more* results narrowing further would leave.
 */
export interface RepoFacets {
  tags: RepoFacetItem[];
  licenses: RepoFacetItem[];
  tasks: RepoFacetItem[];
  /**
   * Relations counts the base model relations present in the result set
   * (LineageRelation, or whatever else a card declared), so the sidebar can
   * offer "quantized (12)". A repository that declares no base model is in
   * no bucket: "base only" is the `base_only=true` filter, not a relation.
   */
  relations: RepoFacetItem[];
}
/**
 * RepoListResponse is one page of a repository listing.
 */
export interface RepoListResponse {
  items: RepoSummary[];
  /**
   * Total is how many repositories match, ignoring the page window.
   */
  total: number /* int64 */;
  /**
   * Facets is only populated for GET /api/v1/repos; the HF-compatible
   * list endpoints leave it as its zero value.
   */
  facets: RepoFacets;
}
/**
 * StatsResponse holds the dashboard counters.
 */
export interface StatsResponse {
  datasets: number /* int64 */;
  models: number /* int64 */;
  experiments: number /* int64 */;
  /**
   * TotalSize is the sum of every visible repository's size, in bytes.
   */
  total_size: number /* int64 */;
}
/**
 * UsageNamespace aggregates one namespace's storage footprint: the actual
 * bytes kept in GCS (the LFS objects its repositories reference -- plain git
 * blobs never leave the repository, so they cost nothing in GCS and are not
 * counted here), how many files are indexed across those repositories, and
 * how many repositories it holds.
 */
export interface UsageNamespace {
  namespace: string;
  lfs_size: number /* int64 */;
  num_files: number /* int64 */;
  num_repos: number /* int64 */;
}
/**
 * UsageRepo is one repository's contribution to storage usage.
 */
export interface UsageRepo {
  namespace: string;
  name: string;
  kind: RepoKind;
  full_name: string;
  lfs_size: number /* int64 */;
  num_files: number /* int64 */;
}
/**
 * UsageResponse is the body of GET /api/v1/usage.
 */
export interface UsageResponse {
  namespaces: UsageNamespace[];
  /**
   * Repos is sorted by LFSSize descending.
   */
  repos: UsageRepo[];
}
/**
 * CommitInfoUI is one commit as the file browser and history views show it.
 */
export interface CommitInfoUI {
  oid: string;
  /**
   * Message is the commit's subject line only.
   */
  message: string;
  author: string;
  date: string;
}
/**
 * TreeEntryUI is one row of the repository file browser.
 */
export interface TreeEntryUI {
  type: EntryType;
  name: string;
  path: string;
  size: number /* int64 */;
  /**
   * LFS reports that the content lives in object storage, not in git.
   */
  lfs: boolean;
  oid: string;
  is_parquet: boolean;
  /**
   * IsModel is set for checkpoint files the model inspector can read.
   */
  is_model: boolean;
  preview: PreviewKind;
  /**
   * LastCommit is the most recent commit that changed this entry, or null
   * when the history walk hit its cap before finding it.
   */
  last_commit: CommitInfoUI | null;
  /**
   * GcloudCommand is a ready-made, shell-quoted `gcloud storage cp` that
   * fetches this entry's bytes from the bucket into ./{name}: the
   * content-addressed lfs/ object for an LFS file, the blobs/ object for any
   * other file. Empty for directories, and for a plain (non-LFS) file whose
   * blob the sync worker has not indexed for rev yet -- the worker publishes
   * to blobs/ before it writes the index, so an indexed blob is promised to
   * be there and an unindexed one (a fresh push, a bare commit) is not.
   */
  gcloud_command: string;
}
/**
 * RepoGCSFile is one file of a revision together with where its bytes live
 * in the bucket.
 */
export interface RepoGCSFile {
  path: string;
  size: number /* int64 */;
  lfs: boolean;
  /**
   * URI is the gs:// URI of the object holding the file's bytes.
   */
  uri: string;
}
/**
 * RepoGCSResponse is what GET /api/v1/repos/{kind}/{ns}/{name}/gcs/{rev}
 * returns: the bucket location of every file on an indexed ref, plus
 * ready-made snippets to fetch them. Objects are content-addressed
 * (lfs/{oid}, blobs/{sha}), so the human-readable layout lives in the
 * destination side of these snippets, never in the bucket.
 */
export interface RepoGCSResponse {
  ref: string;
  files: RepoGCSFile[];
  /**
   * GcloudScript is a POSIX shell script that copies every file to
   * $DEST/{path} with `gcloud storage cp`. DEST defaults to ./{name} and
   * may be a local directory or a gs:// prefix.
   */
  gcloud_script: string;
  /**
   * DuckDBSnippet is a read_parquet() call over the revision's parquet
   * files, or "" when it has none.
   */
  duckdb_snippet: string;
}
/**
 * TreeResponseUI is a directory listing, with the directory's README if it
 * has one.
 */
export interface TreeResponseUI {
  path: string;
  entries: TreeEntryUI[];
  /**
   * Readme is the rendered source of README.md in this directory, or null.
   */
  readme: string | null;
  /**
   * ReadmeTooLarge is true when this directory's README.md exists but
   * exceeds the server's size limit for rendering, in which case Readme is
   * left null instead of silently looking like "no README".
   */
  readme_too_large: boolean;
  /**
   * LatestCommit is the commit the listing was taken at (null for an empty
   * repository).
   */
  latest_commit: CommitInfoUI | null;
}
/**
 * RefUI is one branch or tag of a repository.
 */
export interface RefUI {
  name: string;
  target_oid: string;
}
/**
 * RefsResponseUI feeds the revision picker in the file browser.
 */
export interface RefsResponseUI {
  branches: RefUI[];
  tags: RefUI[];
  default_branch: string;
}
/**
 * CommitListResponse is one page of a revision's history, newest first.
 */
export interface CommitListResponse {
  commits: CommitInfoUI[];
  /**
   * NextCursor is the value to pass as ?after= for the next page, or null
   * when this page reached the root commit.
   */
  next_cursor: string | null;
}
/**
 * RawFileResponse is a file's contents, cut off at the preview limit.
 */
export interface RawFileResponse {
  path: string;
  /**
   * Size is the file's full size, even when Content was truncated.
   */
  size: number /* int64 */;
  truncated: boolean;
  content: string;
  encoding: FileEncoding;
}
/**
 * EditFileRequest saves an in-browser edit as a commit.
 */
export interface EditFileRequest {
  content: string;
  message: string;
  description?: string;
  /**
   * BaseOID is the blob SHA the edit started from. When set, the commit is
   * refused if the path has moved on since, so a save never silently
   * clobbers someone else's concurrent edit. Omit it when creating a file.
   */
  base_oid?: string;
}
/**
 * EditFileResponse reports where the edit landed.
 */
export interface EditFileResponse {
  path: string;
  commit_oid: string;
  oid: string;
  size: number /* int64 */;
}
/**
 * ParquetColumn describes one column of a parquet schema.
 */
export interface ParquetColumn {
  /**
   * Name is the column's name.
   */
  name: string;
  /**
   * Type is the physical parquet type, e.g. "INT64", "BYTE_ARRAY". For
   * non-leaf (nested group) columns this is "GROUP".
   */
  type: string;
  /**
   * LogicalType is the logical type annotation, e.g. "STRING",
   * "TIMESTAMP(MICROS)", "LIST", "MAP", or "" when none is set.
   */
  logical_type: string;
  /**
   * Optional reports whether the column may be null.
   */
  optional: boolean;
  /**
   * Repeated reports whether the column may hold multiple values per row.
   */
  repeated: boolean;
  /**
   * Feature is the Hugging Face `datasets` feature type of the column,
   * lower-cased (e.g. "image", "audio", "classlabel"), when the file or the
   * repository's README declares one; "" otherwise. The viewer reads it
   * from the parquet key-value metadata written by `datasets` (the
   * "huggingface" key) and falls back to the README's
   * `dataset_info.features`. It is a rendering hint only: an "image"
   * column's values are the usual `{bytes, path}` struct or raw bytes.
   */
  feature: string;
}
/**
 * ParquetSchemaResponse describes a parquet file without reading its rows.
 */
export interface ParquetSchemaResponse {
  path: string;
  size: number /* int64 */;
  num_rows: number /* int64 */;
  num_row_groups: number /* int */;
  compression: string;
  columns: ParquetColumn[];
}
/**
 * ParquetRowsResponse is one page of decoded parquet rows.
 */
export interface ParquetRowsResponse {
  path: string;
  /**
   * Offset is the row offset this page starts at.
   */
  offset: number /* int64 */;
  /**
   * Limit is the page size that was applied, after clamping.
   */
  limit: number /* int */;
  /**
   * NumRows is the total number of rows in the file, not just this page.
   */
  num_rows: number /* int64 */;
  /**
   * Columns describes the columns present in Rows, in the requested order.
   */
  columns: ParquetColumn[];
  /**
   * Rows holds one JSON-safe object per row, keyed by column name.
   */
  rows: { [key: string]: unknown}[];
}
/**
 * ModelTensor is one named tensor in a checkpoint.
 */
export interface ModelTensor {
  name: string;
  /**
   * DType is the framework-neutral dtype name, e.g. "float32", "bfloat16".
   */
  dtype: string;
  shape: number /* int64 */[];
  /**
   * NumParameters is the product of Shape (1 for a scalar tensor).
   */
  num_parameters: number /* int64 */;
  /**
   * SizeBytes is NumParameters * the dtype's width, 0 when the width is
   * unknown.
   */
  size_bytes: number /* int64 */;
}
/**
 * ModelDTypeStat aggregates the tensors sharing one dtype.
 */
export interface ModelDTypeStat {
  dtype: string;
  num_tensors: number /* int */;
  num_parameters: number /* int64 */;
  size_bytes: number /* int64 */;
}
/**
 * ModelInfo is everything the inspector learns from a checkpoint's header.
 */
export interface ModelInfo {
  format: ModelFormat;
  /**
   * NumTensors, NumParameters and TensorBytes cover the whole file even
   * when Tensors below is truncated.
   */
  num_tensors: number /* int */;
  num_parameters: number /* int64 */;
  tensor_bytes: number /* int64 */;
  dtypes: ModelDTypeStat[];
  /**
   * Metadata is the file's own metadata: the safetensors `__metadata__`
   * map, or the scalar entries sitting next to the weights in a PyTorch
   * checkpoint (epoch, global_step, ...).
   */
  metadata: { [key: string]: string};
  /**
   * HeaderBytes is the size of the parsed header (the safetensors JSON
   * header or the pickled `data.pkl`).
   */
  header_bytes: number /* int64 */;
  tensors: ModelTensor[];
  /**
   * Truncated reports that Tensors lists only the first few thousand
   * entries; the totals above still cover every tensor.
   */
  truncated: boolean;
  /**
   * Warnings carries recoverable problems, e.g. a structure the reader
   * only understood in part.
   */
  warnings: string[];
}
/**
 * ModelMetaResponse flattens an inspection into the file's own identity, so
 * the UI gets `path` and `size` alongside the header fields.
 */
export interface ModelMetaResponse extends ModelInfo {
  path: string;
  size: number /* int64 */;
}
/**
 * ExpProjectListItem is one experiment repository in the global listing.
 */
export interface ExpProjectListItem {
  namespace: string;
  name: string;
  full_name: string;
  num_projects: number /* int */;
  updated_at: string;
}
/**
 * ExpProjectListResponse is the body of GET /api/v1/experiments.
 */
export interface ExpProjectListResponse {
  items: ExpProjectListItem[];
  /**
   * Total is the number of matching repositories regardless of limit /
   * offset (docs/dev/namespace-design.md §5.6).
   */
  total: number /* int64 */;
}
/**
 * ExpProject is one project (a group of runs) inside an experiment repository.
 */
export interface ExpProject {
  name: string;
  num_runs: number /* int */;
  updated_at: string;
}
/**
 * ExpRepoResponse is an experiment repository together with its projects.
 */
export interface ExpRepoResponse {
  repo: RepoSummary;
  projects: ExpProject[];
}
/**
 * ExpRun is one training run's summary row.
 */
export interface ExpRun {
  name: string;
  status: RunStatus;
  /**
   * LastStep is the highest step seen for this run.
   */
  last_step: number /* int64 */;
  /**
   * NumPoints is how many metric points have been recorded.
   */
  num_points: number /* int64 */;
  /**
   * StartedAt is null for a run recovered from an export that carried no
   * start time.
   */
  started_at: string | null;
  updated_at: string;
  /**
   * Config is the run's hyperparameters, as logged.
   */
  config: { [key: string]: unknown};
  metric_keys: string[];
  /**
   * Summary holds the last value seen for each metric.
   */
  summary: { [key: string]: number /* float64 */};
  /**
   * Group is the sweep this run belongs to, as `trackio.init(group=...)`
   * declared it, and JobType the role it played in that sweep
   * (`job_type=...`). Both are "" for a run that declared neither, which is
   * how the run table tells a sweep member from a standalone run.
   */
  group: string;
  job_type: string;
  /**
   * Tags are free-form labels a user attached to the run.
   */
  tags: string[];
  /**
   * Archived hides the run from the default listing without deleting it.
   */
  archived: boolean;
  /**
   * IsBaseline marks the run every other run is compared against. At most one
   * run per project carries it.
   */
  is_baseline: boolean;
  /**
   * Note is free-form Markdown a user wrote about the run. Like the other
   * annotations it is never written by ingest or by the parquet indexer, so
   * re-indexing the project leaves it in place.
   */
  note: string;
  /**
   * Models are the model repositories this run declared it produced
   * (`trackio.log_model`). Another annotation: ingest and the indexer leave
   * it alone.
   */
  models: ExpRunModelRef[];
}
/**
 * ExpRunModelRef is one model a run recorded as its output.
 */
export interface ExpRunModelRef {
  /**
   * RepoID is the model repository as "ns/name".
   */
  repo_id: string;
  /**
   * Revision is the commit, branch or tag the run pinned, "" when the shim
   * could not resolve one. It is recorded verbatim and never verified: only
   * the repository's existence is checked (see Exists), so a link to a
   * revision that has since been rewritten fails in the file browser rather
   * than being hidden here.
   */
  revision: string;
  /**
   * Exists reports that RepoID resolves to a model repository this viewer
   * may read. A false value means the UI shows text and a warning instead of
   * a link -- the same treatment a dangling lineage reference gets.
   */
  exists: boolean;
}
/**
 * ExpRunModelInput is one entry of a produced-model list being written. Unlike
 * ExpRunModelRef it carries no Exists: that is the server's answer, not the
 * client's claim.
 */
export interface ExpRunModelInput {
  repo_id: string;
  revision?: string;
}
/**
 * ExpRunListResponse is the body of the run listing endpoint.
 */
export interface ExpRunListResponse {
  runs: ExpRun[];
}
/**
 * ExpArtifact is one file a run stored under its artifact directory.
 */
export interface ExpArtifact {
  /**
   * Name is the path relative to the run's artifact directory -- the name
   * `log_artifact` was given, possibly with subdirectories.
   */
  name: string;
  /**
   * Path is the full path inside the repository, which is what the file
   * browser and `resolve` need.
   */
  path: string;
  size: number /* int64 */;
  /**
   * LFS reports that the file is stored as a Git LFS pointer.
   */
  lfs: boolean;
  /**
   * Preview is how the file browser would render this file, so the run page
   * can pick a matching icon and link.
   */
  preview: PreviewKind;
}
/**
 * ExpArtifactListResponse lists one run's artifacts.
 */
export interface ExpArtifactListResponse {
  /**
   * Path is the directory the listing came from,
   * "{project}/artifacts/{run}" (docs/dev/api-contract.md §7).
   */
  path: string;
  /**
   * Rev is the revision listed, always the repository's default branch.
   */
  rev: string;
  artifacts: ExpArtifact[];
}
/**
 * ExpRunAnnotationRequest is a partial update of a run's annotations: an
 * omitted field is left as it is, so a client can toggle one flag without
 * having to send the rest.
 */
export interface ExpRunAnnotationRequest {
  tags?: string[];
  archived?: boolean;
  is_baseline?: boolean;
  note?: string;
  /**
   * Models replaces the run's produced-model list wholesale; an empty array
   * clears it. This is the write path behind `trackio.log_model`.
   */
  models?: ExpRunModelInput[];
}
/**
 * ExpRunAnnotationResponse returns the run as it stands after the update.
 */
export interface ExpRunAnnotationResponse {
  run: ExpRun;
}
/**
 * ExpMetricSeries is one metric's trace for one run, as [x, y] pairs.
 */
export interface ExpMetricSeries {
  run: string;
  key: string;
  points: MetricPoint[];
}
/**
 * ExpMetricsResponse carries the traces a chart asked for.
 */
export interface ExpMetricsResponse {
  series: ExpMetricSeries[];
}
/**
 * LineageEdgeKind names the sort of provenance one lineage edge records.
 */
/**
 * LineageEdgeKindDataset points at a dataset the repository was built from.
 */
export const LineageEdgeKindDataset = "dataset";
/**
 * LineageEdgeKindBaseModel points at the checkpoint it started from.
 */
export const LineageEdgeKindBaseModel = "base_model";
/**
 * LineageEdgeKindRun points at the experiment run that produced it.
 */
export const LineageEdgeKindRun = "run";
/**
 * LineageEdgeKindEvalDataset points at a dataset the repository was
 * evaluated on, which is a different claim from having trained on it.
 */
export const LineageEdgeKindEvalDataset = "eval_dataset";
/**
 * LineageEdgeKindNewVersion points at the repository that supersedes this
 * one. It is the only kind that targets a repository of its own kind, and
 * it does not appear in RepoLineageResponse.Upstream: the resolved chain
 * in NewVersion says the same thing more usefully.
 */
export const LineageEdgeKindNewVersion = "new_version";
export type LineageEdgeKind = typeof LineageEdgeKindDataset | typeof LineageEdgeKindBaseModel | typeof LineageEdgeKindRun | typeof LineageEdgeKindEvalDataset | typeof LineageEdgeKindNewVersion;
/**
 * LineageRelation names how a repository relates to the base model it points
 * at -- HuggingFace Hub's `base_model_relation`. A card may declare it
 * outright; when it does not, the sync worker infers it from the repository's
 * contents (docs/dev/api-contract.md §12).
 * The wire fields carrying it are plain strings, not this type: a card is free
 * to write something outside the four known values, and such a value is passed
 * through verbatim rather than being rewritten into a lie. These constants are
 * the set the UI groups by; everything else belongs under "other".
 */
/**
 * LineageRelationFinetune is further training from the base model's own
 * weights. It is the default when nothing more specific applies.
 */
export const LineageRelationFinetune = "finetune";
/**
 * LineageRelationAdapter is a LoRA/PEFT adapter over the base model.
 */
export const LineageRelationAdapter = "adapter";
/**
 * LineageRelationQuantized is the base model at a lower precision.
 */
export const LineageRelationQuantized = "quantized";
/**
 * LineageRelationMerge is a blend of two or more base models.
 */
export const LineageRelationMerge = "merge";
export type LineageRelation = typeof LineageRelationFinetune | typeof LineageRelationAdapter | typeof LineageRelationQuantized | typeof LineageRelationMerge;
/**
 * LineageRef is one upstream reference a repository card declares.
 */
export interface LineageRef {
  kind: LineageEdgeKind;
  /**
   * Raw is the reference exactly as the card spelled it, e.g.
   * "team/imdb-ja@v1". It is the only field worth showing when Exists is
   * false.
   */
  raw: string;
  /**
   * TargetKind is the repository kind this edge points at. Dataset and run
   * edges both target dataset repositories: experiment logs live in one.
   */
  target_kind: RepoKind;
  /**
   * Namespace, Name and FullName are the normalised target, all "" when the
   * raw reference does not parse as one.
   */
  namespace: string;
  name: string;
  full_name: string;
  /**
   * Rev is the branch, tag or commit the reference pinned, "" for none.
   */
  rev: string;
  /**
   * Project and Run are set on run edges only.
   */
  project: string;
  run: string;
  /**
   * Relation is how this repository relates to the base model it names --
   * one of LineageRelation, or whatever else the card declared. Set on
   * base_model edges only; "" on dataset and run edges.
   */
  relation: string;
  /**
   * Exists reports that the target resolves to a repository. A false value
   * means the UI must render plain text, not a link: the reference may be a
   * typo, or may not have been pushed yet.
   */
  exists: boolean;
}
/**
 * LineageDependent is one repository that names this repository -- or one of
 * its runs -- as part of its own origin.
 */
export interface LineageDependent {
  repo: RepoSummary;
  kind: LineageEdgeKind;
  /**
   * Raw is the dependent's own reference string, which shows how it pinned
   * this repository.
   */
  raw: string;
  rev: string;
  /**
   * Project and Run name the run the dependent came from, on run edges only.
   */
  project: string;
  run: string;
  /**
   * Relation is how the dependent describes itself relative to this
   * repository -- one of LineageRelation, or whatever else its card
   * declared. Set on base_model edges only; "" on dataset and run edges.
   * It is what the model tree groups the derived repositories by.
   */
  relation: string;
}
/**
 * LineageSuccessor is where a repository's `new_version:` declaration leads:
 * the successor its own card names, and the end of the chain that successor
 * starts (docs/dev/api-contract.md §12).
 */
export interface LineageSuccessor {
  /**
   * Direct is the successor this repository's card names outright. It is
   * the only field with anything in it when the reference is dangling, in
   * which case Direct.Exists is false and Hops is 0.
   */
  direct: LineageRef;
  /**
   * Latest is the newest version reachable by following `new_version:` from
   * one repository to the next -- what a reader should be sent to. It
   * equals Direct for a one-hop chain, and also whenever Truncated is set.
   */
  latest: LineageRef;
  /**
   * Hops is how many edges were followed to reach Latest: 1 for a direct
   * successor, 0 when the declared successor does not resolve.
   */
  hops: number;
  /**
   * Truncated reports that the chain never ended -- it formed a cycle, or
   * ran past the walk's depth limit. Latest is then the direct successor
   * only, and the UI must not claim it is the newest version.
   */
  truncated: boolean;
}
/**
 * RepoLineageResponse is a repository's provenance in both directions.
 */
export interface RepoLineageResponse {
  /**
   * Upstream is what this repository's card declares it came from.
   */
  upstream: LineageRef[];
  /**
   * Downstream is the reverse lookup: repositories whose cards point here.
   */
  downstream: LineageDependent[];
  /**
   * NewVersion is the successor the card declares, resolved through the
   * chain of successors behind it, or null when the card declares none.
   * Successor edges are reported here instead of in Upstream: they point
   * forward in time, not back at an origin.
   */
  new_version: LineageSuccessor | null;
  /**
   * ProducedBy lists the experiment runs that declared this repository as
   * their output (`trackio.log_model`). It is separate from the `run` edges
   * in Upstream because the claim comes from the other end: those are what
   * this repository's own card says, these are what a training script said.
   * Empty for anything but a model repository.
   */
  produced_by: ExpRunProducer[];
}
/**
 * ExpRunProducer is one experiment run that declared it produced a model.
 */
export interface ExpRunProducer {
  /**
   * Repo is the experiment *dataset* repository the run lives in (§7).
   */
  repo: RepoSummary;
  project: string;
  run: string;
  /**
   * Revision is the revision of the produced model the run recorded, "" if
   * it could not resolve one.
   */
  revision: string;
}
/**
 * ExpRunLineage lists the repositories one experiment run produced.
 */
export interface ExpRunLineage {
  run: string;
  models: LineageDependent[];
}
/**
 * ExpLineageResponse carries the run-to-model links of an experiment project.
 */
export interface ExpLineageResponse {
  items: ExpRunLineage[];
}
/**
 * RepoTransferStatus is the lifecycle state of a transfer request
 * (docs/dev/repo-transfer-design.md §7).
 */
export type RepoTransferStatus = string;
export const RepoTransferPending: RepoTransferStatus = "pending";
export const RepoTransferAccepted: RepoTransferStatus = "accepted";
export const RepoTransferRejected: RepoTransferStatus = "rejected";
export const RepoTransferCancelled: RepoTransferStatus = "cancelled";
export const RepoTransferExpired: RepoTransferStatus = "expired";
/**
 * RepoTransferRequest asks to move a repository to another namespace (and
 * optionally rename it at the same time).
 */
export interface RepoTransferRequest {
  /**
   * Namespace is the destination user or organisation.
   */
  namespace: string;
  /**
   * Name is the new repository name; empty keeps the current one.
   */
  name?: string;
}
/**
 * RepoTransfer is one transfer request as the web UI sees it.
 */
export interface RepoTransfer {
  id: number /* int64 */;
  kind: RepoKind;
  from_namespace: string;
  from_name: string;
  to_namespace: string;
  to_name: string;
  requested_by: string;
  status: RepoTransferStatus;
  expires_at: string;
  created_at: string;
}
/**
 * RepoTransferResponse answers a transfer call. Repo is present only when the
 * move completed (immediately, or on accept) and describes the repository at
 * its new location.
 */
export interface RepoTransferResponse {
  transfer: RepoTransfer;
  repo?: RepoDetail;
}
/**
 * MyTransfersResponse lists the pending transfers the signed-in user can act
 * on: Incoming ones they may accept or reject, Outgoing ones they may cancel.
 */
export interface MyTransfersResponse {
  incoming: RepoTransfer[];
  outgoing: RepoTransfer[];
}
/**
 * OrgRole is a member's role in an organisation. "" means "not a member".
 */
export const OrgRoleAdmin = "admin";
export const OrgRoleWrite = "write";
export const OrgRoleRead = "read";
export type OrgRole = typeof OrgRoleAdmin | typeof OrgRoleWrite | typeof OrgRoleRead;
/**
 * MembersVisibility says who may list an organisation's members.
 */
export const MembersVisibilityMembers = "members";
export const MembersVisibilityPublic = "public";
export type MembersVisibility = typeof MembersVisibilityMembers | typeof MembersVisibilityPublic;
/**
 * Org is one organisation as the web UI sees it.
 */
export interface Org {
  name: string;
  display_name: string;
  description: string;
  website: string;
  avatar_url: string;
  /**
   * MembersVisibility is about the member list, not about repositories:
   * there is no repository visibility concept here
   * (docs/dev/content-addressed-storage-design.md §1).
   */
  members_visibility: MembersVisibility;
  num_members: number /* int64 */;
  num_repos: number /* int64 */;
  created_at: string;
  /**
   * ViewerRole is the caller's effective role ("admin" for a site admin,
   * "" when signed out or not a member).
   */
  viewer_role: OrgRole;
}
/**
 * OrgMember is one membership row.
 */
export interface OrgMember {
  username: string;
  /**
   * Email is "" when the member list is being viewed by a non-member
   * (members_visibility = "public").
   */
  email: string;
  role: OrgRole;
  created_at: string;
}
/**
 * OrgAuditEntry is one line of an organisation's audit log.
 */
export interface OrgAuditEntry {
  id: number /* int64 */;
  /**
   * Actor is the username that performed the action ("" when the account
   * has since been deleted and nothing was recorded).
   */
  actor: string;
  action: string;
  /**
   * Target is the affected username, repository full name, or webhook URL,
   * depending on Action.
   */
  target: string;
  details: { [key: string]: unknown};
  created_at: string;
}
/**
 * OrgCreateRequest is the body of POST /api/v1/orgs.
 */
export interface OrgCreateRequest {
  name: string;
  display_name?: string;
  description?: string;
}
/**
 * OrgUpdateRequest is the body of PATCH /api/v1/orgs/{org}. Every field is
 * optional; absent ones are left unchanged.
 */
export interface OrgUpdateRequest {
  display_name?: string;
  description?: string;
  website?: string;
  avatar_url?: string;
  members_visibility?: MembersVisibility;
}
/**
 * OrgMemberAddRequest is the body of POST /api/v1/orgs/{org}/members.
 */
export interface OrgMemberAddRequest {
  username: string;
  /**
   * Role defaults to "read" when empty.
   */
  role?: OrgRole;
}
/**
 * OrgMemberUpdateRequest is the body of PATCH /api/v1/orgs/{org}/members/{username}.
 */
export interface OrgMemberUpdateRequest {
  role: OrgRole;
}
/**
 * OrgResponse wraps one organisation.
 */
export interface OrgResponse {
  org: Org;
}
/**
 * OrgListResponse is the body of GET /api/v1/orgs and GET /api/v1/me/orgs.
 */
export interface OrgListResponse {
  items: Org[];
  total: number /* int64 */;
}
/**
 * OrgMembersResponse is the body of GET /api/v1/orgs/{org}/members.
 */
export interface OrgMembersResponse {
  items: OrgMember[];
}
/**
 * OrgMemberResponse wraps one membership row.
 */
export interface OrgMemberResponse {
  member: OrgMember;
}
/**
 * OrgAuditLogResponse is one page of GET /api/v1/orgs/{org}/audit-log.
 * NextBefore is the cursor for the following page, 0 when this was the last.
 */
export interface OrgAuditLogResponse {
  items: OrgAuditEntry[];
  next_before: number /* int64 */;
}
/**
 * WebhookEvent names one kind of event a webhook may subscribe to.
 */
export const WebhookEventRepoPush = "repo.push";
export const WebhookEventRepoCreated = "repo.created";
export const WebhookEventRepoDeleted = "repo.deleted";
/**
 * WebhookEventRepoMoved fires after a repository was transferred or
 * renamed; delivered to the *new* namespace's subscriptions.
 */
export const WebhookEventRepoMoved = "repo.moved";
/**
 * WebhookEventRepoTransferRequested fires when a transfer needs the
 * destination namespace's approval; delivered to that namespace.
 */
export const WebhookEventRepoTransferRequested = "repo.transfer_requested";
/**
 * WebhookEventRepoArchived / RepoUnarchived fire when a repository is
 * frozen read-only and when it is thawed again. Mirroring systems care:
 * an archived repository will not change until it is unarchived.
 */
export const WebhookEventRepoArchived = "repo.archived";
export const WebhookEventRepoUnarchived = "repo.unarchived";
export const WebhookEventRunFinished = "run.finished";
export const WebhookEventRunFailed = "run.failed";
export type WebhookEvent = typeof WebhookEventRepoPush | typeof WebhookEventRepoCreated | typeof WebhookEventRepoDeleted | typeof WebhookEventRepoMoved | typeof WebhookEventRepoTransferRequested | typeof WebhookEventRepoArchived | typeof WebhookEventRepoUnarchived | typeof WebhookEventRunFinished | typeof WebhookEventRunFailed;
/**
 * WebhookDeliveryStatus is the lifecycle state of one delivery attempt.
 */
export type WebhookDeliveryStatus = string;
export const WebhookDeliveryPending: WebhookDeliveryStatus = "pending";
export const WebhookDeliverySuccess: WebhookDeliveryStatus = "success";
export const WebhookDeliveryFailed: WebhookDeliveryStatus = "failed";
/**
 * Webhook is one subscription as the web UI sees it. Secret is included only
 * in the response to a create call (see CreateWebhookResponse); every other
 * response omits it.
 */
export interface Webhook {
  id: number /* int64 */;
  namespace: string;
  /**
   * RepoFullName is "" for a namespace-wide subscription, "ns/name"
   * when scoped to one repository.
   */
  repo_full_name: string;
  url: string;
  events: WebhookEvent[];
  active: boolean;
  created_at: string;
  updated_at: string;
}
/**
 * WebhookListResponse is the body of GET .../webhooks.
 */
export interface WebhookListResponse {
  items: Webhook[];
}
/**
 * WebhookResponse wraps a single webhook.
 */
export interface WebhookResponse {
  webhook: Webhook;
}
/**
 * CreateWebhookRequest is the body of POST .../webhooks.
 */
export interface CreateWebhookRequest {
  /**
   * Repo is "" for a namespace-wide webhook, or "kind/name" (e.g.
   * "dataset/my-metrics") to scope it to one repository in the namespace.
   */
  repo?: string;
  url: string;
  events: WebhookEvent[];
  /**
   * Active defaults to true when omitted; the field exists so a webhook can
   * be created disabled.
   */
  active?: boolean;
}
/**
 * CreateWebhookResponse returns the freshly minted webhook including its
 * secret, which is never shown again — a client that loses it must rotate it
 * via UpdateWebhookRequest.
 */
export interface CreateWebhookResponse extends Webhook {
  secret: string;
}
/**
 * UpdateWebhookRequest patches a webhook. Nil/omitted fields are left
 * unchanged; Events, when present, replaces the whole set. Setting
 * RotateSecret regenerates the secret, returned once in the response.
 */
export interface UpdateWebhookRequest {
  url?: string;
  events?: WebhookEvent[];
  active?: boolean;
  rotate_secret?: boolean;
}
/**
 * UpdateWebhookResponse carries the new secret only when the update rotated
 * it.
 */
export interface UpdateWebhookResponse extends Webhook {
  /**
   * Secret is set only when the request rotated it.
   */
  secret?: string;
}
/**
 * WebhookDelivery is one delivery attempt's history row.
 */
export interface WebhookDelivery {
  id: number /* int64 */;
  event: WebhookEvent;
  payload: { [key: string]: unknown};
  status: WebhookDeliveryStatus;
  attempts: number /* int */;
  last_attempt_at: string | null;
  response_status: number | null;
  response_body: string;
  created_at: string;
}
/**
 * WebhookDeliveryListResponse is one page of a webhook's delivery history.
 */
export interface WebhookDeliveryListResponse {
  items: WebhookDelivery[];
  total: number /* int64 */;
}
/**
 * ApiError describes what went wrong.
 */
export interface ApiError {
  message: string;
  type: string;
  /**
   * MovedTo is set (with Type "repo_moved", status 404) when the requested
   * repository name is a former name of a repository that has since been
   * transferred or renamed; the client should retry at the new location.
   */
  moved_to?: RepoLocation;
}
/**
 * RepoLocation names a repository by namespace and name.
 */
export interface RepoLocation {
  namespace: string;
  name: string;
}
/**
 * ApiErrorBody is the body of every non-2xx API response.
 */
export interface ApiErrorBody {
  error: ApiError;
}
